# Récupère les données de l'ontologie au format xlsx depuis google drive pour les transformer au format turtle.
name: Google Sheet to TTL
on: workflow_dispatch     
jobs:
  google-sheet-to-ttl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run : |
          curl -L --request GET 'https://xls2rdf.sparna.fr/rest/convert?noPostProcessings=true' \
          -H "Connection: keep-alive" \
          -F url='https://docs.google.com/spreadsheets/d/1CZIf3bxuuH3aghFn7B7P89DrLqp_jzv4moI_BpI9PzY/export?format=xlsx' \
          -F format=ttl \
          -o ./profil-application/rdafr-schacl.ttl
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Feat : Mise à jour de l'ontologie"
